// <auto-generated />
using System;
using ChurrasTrinca.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChurrasTrinca.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    partial class MeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChurrasTrinca.Business.Models.Churras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<double>("ValorArrecadado");

                    b.Property<double>("ValorComBebida");

                    b.Property<double>("ValorSemBebida");

                    b.HasKey("Id");

                    b.ToTable("Churras");
                });

            modelBuilder.Entity("ChurrasTrinca.Business.Models.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ChurrasId");

                    b.Property<bool>("ComBebida");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Pago");

                    b.Property<double>("ValorPago");

                    b.HasKey("Id");

                    b.HasIndex("ChurrasId");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("ChurrasTrinca.Business.Models.Participante", b =>
                {
                    b.HasOne("ChurrasTrinca.Business.Models.Churras", "Churras")
                        .WithMany("Participantes")
                        .HasForeignKey("ChurrasId");
                });
#pragma warning restore 612, 618
        }
    }
}
